name: nordvpn
services:
  nordvpn:
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: []
    container_name: nordvpn
    environment:
      LAN_DISCOVERY: "On"
      MESHNET: enabled
      NET_LOCAL: 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8
      PGID: $PGID
      PORTS: 53,80;443,51820
      PUID: $GUID
      TECHNOLOGY: NordLynx
      TOKEN: <API Token>
      TZ: $TZ
    hostname: nordvpn
    image: ghcr.io/bubuntux/nordvpn:latest
    ports:
      - target: 51820
        published: "51820"
        protocol: udp
    restart: unless-stopped
x-casaos:
  author: self
  category: VPN
  hostname: ""
  icon: https://cdn.iconscout.com/icon/free/png-256/free-nordvpn-7662268-6297204.png
  index: /
  port_map: ""
  scheme: http
  store_app_id: nordvpn
  tips:
    custom: Use this to get the private key from the token
  title:
    custom: NordVPN
