name: barcode-buddy
services:
  barcode-buddy:
    command: []
    container_name: barcode-buddy
    environment:
      ATTACH_BARCODESCANNER: "false"
      PGID: $PGID
      PUID: $PUID
      TZ: $TZ
    x-casaos:
      envs:
        - container: ATTACH_BARCODESCANNER
          description:
            en_us: "Boolean to utilize a hardware barcode scanner"
    hostname: barcode-buddy
    image: f0rc3/barcodebuddy:latest
    ports:
      - target: 80
        published: ${WEBUI_PORT:-8080}
        protocol: tcp
      - target: 443
        published: "9443"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
x-casaos:
  author: self
  developer: Forceu
  category: Home Automation
  hostname: ""
  icon: https://f-droid.org/repo/de.bulling.barcodebuddyscanner/en-US/icon_d-5wBjXTL7QHBSxVkiddVKoBI-_8fx9NVMtHAfbIZSE=.png
  index: /
  port_map: ${WEBUI_PORT:-8080}
  scheme: http
  store_app_id: barcode-buddy
  architectures: # a list of architectures that the app supports
    - amd64
  title:
    en_us: Barcode Buddy
    zh_cn: 条码助手
    fr_fr: Compagnon de code-barres
    es_es: Compañero de códigos de barras
    de_de: Barcode-Buddy
    ru_ru: Помощник по штрих-кодам
    it_it: Compagno di codici a barre
    pt_br: Parceiro de código de barras
    tr_tr: Barkod Arkadaşı
    pl_pl: Asystent kodów kreskowych
    ko_kr: 바코드 버디
    ja_jp: バーコードバディ
  description:
    en_us: Barcode system for Grocy
    zh_cn: Grocy 条形码系统
    fr_fr: Système de code-barres pour Grocy
    es_es: Sistema de códigos de barras para Grocy
    de_de: Barcode-System für Grocy
    ru_ru: Система штрих-кодов для Grocy
    it_it: Sistema di codici a barre per Grocy
    pt_br: Sistema de código de barras para Grocy
    tr_tr: Grocy için barkod sistemi
    pl_pl: System kodów kreskowych dla Grocy
    ko_kr: Grocy용 바코드 시스템
    ja_jp: Grocy用バーコードシステム
  tagline:
    en_us: Barcode system for Grocy
    zh_cn: Grocy 条形码系统
    fr_fr: Système de code-barres pour Grocy
    es_es: Sistema de códigos de barras para Grocy
    de_de: Barcode-System für Grocy
    ru_ru: Система штрих-кодов для Grocy
    it_it: Sistema di codici a barre per Grocy
    pt_br: Sistema de código de barras para Grocy
    tr_tr: Grocy için barkod sistemi
    pl_pl: System kodów kreskowych dla Grocy
    ko_kr: Grocy용 바코드 시스템
    ja_jp: Grocy用バーコードシステム
